#+OPTIONS: toc:nil

|----------------------------------------------|
| Humidity wet reverb                          |
|----------------------------------------------|
| Temperature: mapped to the distortion factor |
|----------------------------------------------|
| Trucks: certain sound, when do they happen   |
|----------------------------------------------|
| particles that exceed a certain threshold,   |
| form the melody, pitch, harmony              |
|----------------------------------------------|
| Soundscape Basis                             |
| Filtered Noise / low freq sine wave synth    |
| Mapped to the noise levels                   |
| Linear mapping                               |
|----------------------------------------------|


World Heath Org https://bit.ly/3ODLXh1

Coarse particulate matter *(PM10)*
*45 μg/m3* 24-hour mean

Fine particulate matter *(PM2.5)*
*15 μg/m3* 24-hour mean
12 is better https://bit.ly/3vzPvYU


|------------------------+-----------------------|
| pm10: big particles    | healthy lvls: 45mg/m3 |
|------------------------+-----------------------|
| pm2.5: small particles | healthy lvls: 12mg/m3 |
|------------------------+-----------------------|

what is important to consider is also the fact that the detuning of the synth should not begin from the dangerous value. Should begin earlier bc dangerous level should warn you.

+ consider staying in Rome till Sunday => 7 - 11 of June

modulation: Mix(LFTri+Pulse) => Gradually move from triangle to Pulse


* General Description
General Soundscape: Generally, I would like to represent concerning values, using sonification.  At the same time, what is also important is how all that data are represented with sound.  In particular, musical perception as well as aesthetics should also be taken into account.  For example, big amount of particles is bad, especially when a certain level is exceeded, different for PM10 and PM2.5.  The listener should not only be warned that the particle level is more than the recommended but also the auditory characteristics should convey that.  So, to make this very simple.  As long as the data values are bad, harmful the sonification should sound worse or disturbing in terms of aesthetics.

Moving on now to the data.  We have humidity, temperature, number of trucks, 2 types of particle data (PM10, PM2.5), noise levels.  Right now I am in the process of trying to identify how each type of data can be represented in the sonification in a meaningful way.  For example, I was thinking that the noise levels can be represented with actual noise sounds, XSXSXSXSXSXSXS that whenever the values go high the noise levels is increasing as well.

A rough idea of the mapping regarding particles would be that as long as the particles in the air remain at a low level this should sound good.  How can this be implemented?  I thought about using an ancient Greek musical scale, which is called Λυδικός, Lydian in English.  This scale was used for children's songs, it is described by the ancient Greeks as soft and pleasant.  However, while particles go up high they violate the actual positions of the Lydian scale resulting to a disturbing totality.  While other additional factors, such as distortion, can be also instrumental in making the sonification sound bad, disturbing.

In addition, it is also important that the user should be able to control the whole system, so interactivity is also an another aspect of the project.  I have not thought a lot about this so at the moment I only have a small slider for datetime selection.  The visual representation is also a question, how it would be meaningful that these data can be represented.  Maybe a map?  A line graph?  A scatter plot? Or something completely different?
